language: node_js
node_js:
  - "0.10"

services:
  - redis-server

before_install:
  - npm install -g npm

before_script:
  - git clone https://github.com/vladikoff/freight-server.git && cd freight-server
  - git checkout 29ce236b4a59d4859d9caca6b0c30bdaf493250a
  - npm install && npm link ../
  - NODE_ENV=test npm start &
  - sleep 20
  - cd ..

script:
  - mocha test/*.js --reporter=spec
