language: node_js
node_js:
  - "0.10"

services:
  - redis-server

before_install:
  - npm install -g npm

before_script:
  - npm install vladikoff/freight-server#abb584e0aa86b33b33d3f21680bb2db53e645600
  - cd node_modules/freight-server
  - NODE_ENV=test npm start &
  - sleep 5
  - cd ../..

script:
  - npm test
