language: node_js
node_js:
  - "0.10"

services:
  - redis-server

before_install:
  - npm install -g npm

before_script:
  - npm install vladikoff/freight-server#29ce236b4a59d4859d9caca6b0c30bdaf493250a

script:
  - npm link .
  - cd node_modules/freight-server
  - NODE_ENV=test npm start &
  - sleep 20
  - cd ../..
  - mocha test/*.js --reporter=spec
