language: node_js
node_js:
  - "0.10"

services:
  - redis-server

before_install:
  - npm install -g npm

before_script:
  - git clone https://github.com/vladikoff/freight-server.git && cd freight-server
  - git checkout 8e3e7f9b96289f2e6a9609dc34f73c15c4a1ddf0
  - npm install && npm link ../
  - NODE_ENV=test LOG_LEVEL=debug npm start &
  - sleep 20
  - cd ..

script:
  - node_modules/.bin/grunt jshint
  - mocha test/*.js --reporter=spec
